require:
  - rubocop-rails

AllCops:
  NewCops: enable
  TargetRubyVersion: 3.4
  # Exclude:
  #   - '**/db/schema.rb'
  #   - '**/db/**/*'
  #   - 'bin/*'

Style/FrozenStringLiteralComment:
  Enabled: false

Style/ClassAndModuleChildren:
  Enabled: false

Metrics/BlockLength:
  Enabled: false

Layout/LineLength:
  Enabled: false

Metrics/AbcSize:
  Enabled: false

Metrics/MethodLength:
  Enabled: false

Style/Documentation:
  Enabled: false
# bundle exec rubocop -A --only Style/StringLiterals
# bundle exec rubocop -A --only Rails/RefuteMethods
# bundle exec rubocop -A --only Rails/RootPathnameMethods
# bundle exec rubocop -A --only Rails/FilePath
# bundle exec rubocop -A --only Layout/IndentationWidth
# bundle exec rubocop -A --only Style/SymbolArray
# bundle exec rubocop -A --only Style/WordArray
# bundle exec rubocop -A --only Layout/SpaceInsideArrayLiteralBrackets
# bundle exec rubocop -A --only Style/NumericLiterals
# bundle exec rubocop -A --only Lint/UnusedMethodArgument
# bundle exec rubocop -A --only Layout/MultilineOperationIndentation
