# Omakase Ruby styling for Rails

# Overwrite or add rules to create your own house style
#
# # Use `[a, [b, c]]` not `[ a, [ b, c ] ]`
# Layout/SpaceInsideArrayLiteralBrackets:
#   Enabled: false

require:
  - rubocop-rails

AllCops:
  NewCops: enable
  TargetRubyVersion: 3.4
  Exclude:
    - vendor/bundle/**/*
    - '**/db/schema.rb'
    - '**/db/**/*'
    - 'config/**/*'
    - 'bin/*'
    - 'config.ru'
    - 'Rakefile'

FrozenStringLiteralComment:
  Enabled: false

inherit_mode:
  merge:
    - Exclude

Style/Documentation:
  Enabled: false

Style/ClassAndModuleChildren:
  Enabled: false

Rails/Output:
  Enabled: false

Style/EmptyMethod:
  Enabled: false

Bundler/OrderedGems:
  Enabled: false

Lint/UnusedMethodArgument:
  Enabled: false

Metrics/PerceivedComplexity:
  Enabled: false

Rails/RenderInline:
  Enabled: false

Lint/MissingSuper:
  Enabled: false

Metrics/BlockLength:
  Enabled: false

Metrics/AbcSize:
  Enabled: false

Metrics/MethodLength:
  Enabled: false

Metrics/CyclomaticComplexity:
  Enabled: false

Naming/VariableNumber:
  Exclude:
    - 'test/**/*'

Layout/LineLength:
  Enabled: false

Metrics/ClassLength:
  Exclude:
    - 'app/avo/**/*'

Style/StringLiterals:
  EnforcedStyle: double_quotes

Layout/SpaceInsideArrayLiteralBrackets:
  Enabled: false

Style/OpenStructUse:
  Enabled: false

Naming/PredicateMethod:
  Enabled: false
