databases:
  - name: mysite
    region: frankfurt
    ipAllowList: []
    plan: basic-256mb

services:
  - type: web
    name: mysite
    runtime: ruby
    plan: starter
    region: frankfurt
    buildCommand: bundle install && bundle exec rails assets:precompile && bundle exec rails assets:clean
    preDeployCommand: "bundle exec rails db:migrate"
    startCommand: bundle exec rails server
    healthCheckPath: "/up"
    envVars:
      - key: RAILS_MASTER_KEY
        sync: false
      - key: WEB_CONCURRENCY
        value: 2
      - key: DATABASE_URL
        fromDatabase:
          name: mysite
          property: connectionString
      - key: SOLID_QUEUE_IN_PUMA
        value: "true"